services:

  drupal:
    container_name: drupal
    image: drupal:11.3.2-php8.4-apache-bookworm
    ports:
      - 8080:80
    volumes:
      #- ~/development/php/drupal:/var/www/html
      - ./tzone.ini:/usr/local/etc/php/conf.d/tzone.ini:ro
      - drupal:/var/www/html
      #- drupal:/var/www/html/modules
      #- drupal:/var/www/html/profiles
      #- drupal:/var/www/html/themes
      #- drupal:/var/www/html/sites
    networks:
      - php-docker-stack_default
    environment:
      - TZ=America/Guatemala

volumes:
  drupal:
    name: drupal

networks:
  php-docker-stack_default:
    external: true
