services:

  drupal_intranet:
    container_name: drupal_intranet
    image: drupal:11.3.2-php8.4-apache-bookworm
    ports:
      - 80:80
    volumes:
      - ./tzone.ini:/usr/local/etc/php/conf.d/tzone.ini:ro
      - ~/development/projects/php/intranet:/var/www/html
      #- drupal_intranet:/var/www/html
      #- drupal:/var/www/html/modules
      #- drupal:/var/www/html/profiles
      #- drupal:/var/www/html/themes
      #- drupal:/var/www/html/sites
    networks:
      - php-docker-stack_default
    environment:
      - TZ=America/Guatemala

networks:
  php-docker-stack_default:
    external: true

#volumes:
#  drupal_intranet:
#    name: drupal_intranet
